### PR TITLE
Update popup.html

### PR DESCRIPTION
**Pull request by HackerGaucho**
adjust the image size to prevent it from charging at full resolution when opening the popup

### CODE REVIEW

**Comment by proginosko** [comment]
Is this an issue mainly on Android?

**Comment by HackerGaucho** [comment]
i did not check on Android, I detected this problem only on the desktop with Firefox

**Comment by proginosko** [comment]
Thanks. Can you post a screenshot to illustrate the problem?

**Comment by HackerGaucho** [comment]
No. it's so fast that it's hard to reproduce it, plus other things can hinder the process like:
- the battery charge
- the number of open applications
- the number of enabled extensions

either way, specifying the image size manually I believe the  [image reflow bug](https://browserdiet.com/en/#repaints-and-reflows) will be fixed.

**Comment by proginosko** [comment]
No worries.

**Pull request merged**
