### PR TITLE
Add Vietnamese translation

### PR DESCRIPTION
**Pull request by anhkhoakz**

### CODE REVIEW

**Comment by proginosko** [comment]
Thanks for this! Can you please confirm the translations for `addSiteMenuItem` and `addSiteToBlockSetMenuItem` in **message.json**? They should not be the same as for `addPageMenuItem` and `addPageToBlockSetMenuItem`.

**Comment by anhkhoakz** [comment]
"Trang" is the Vietnamese word for "site" or "page." For that reason, the page will continue to be referred to as "trang" and the site will be translated to "trang web" if possible.

Do you agree with that?

**Comment by proginosko** [comment]
But the labels for the "Add Site" and "Add Page" menu items are identical. That will be confusing for users. How do Vietnamese speakers normally distinguish between "website" and "webpage"?

**Comment by anhkhoakz** [comment]
Maybe can use "địa chỉ web" for website and "trang web" for webpage

**Comment by proginosko** [comment]
> Maybe can use "địa chỉ web" for website and "trang web" for webpage

Sounds good to me. As long as the user can distinguish between blocking an entire site and blocking a single page.

**Comment by proginosko** [comment]
What about "tên miền web" ("web domain"), since "Add Site" adds only the website's domain name to the list?

**Comment by anhkhoakz** [comment]
Yeah, that's sound better. I will make a pull request soon

**Pull request merged**
