### PR TITLE
Change storage to use sync 

### LINKED ISSUE #19: Sync settings among browsers with Firefox sync
It should not be complicated to implement:
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/storage/sync

Btw. 
Thank you for quick implementing of the web-extensions version of this amazing add-on.

### PR DESCRIPTION
**Pull request by torbica**
according to https://wiki.mozilla.org/WebExtensions/chrome.storage.sync this should be easy way to store settings in profile 

I was using this without any problems for couple days. 

This improvement will fix #19

### CODE REVIEW

**Comment by aprokop** [comment]
Are there issues preventing this PR from merging? This feature would be very useful.

**Comment by proginosko** [comment]
Two issues:
1. There are many other places in the code where storage is accessed.
2. What about users who don't want to sync their settings?

Basically, I need to research more how synced storage works before I implement this feature. If it isn't done right, it will mess things up for everyone.

**Comment by arrizalamin** [comment]
@proginosko uBlock has [a button](https://github.com/gorhill/uBlock/wiki/Cloud-storage) to manually export and import settings to browser's cloud storage. You don't need to change how storage is accessed from code, just 2 buttons to export/import extension's local storage to browser's cloud storage.

**Comment by proginosko** [comment]
Working on this right now. Next version will have both options: (1) manual export-to/import-from sync storage and (2) use sync storage automatically instead of local storage.

**Comment by proginosko** [comment]
Sync support added in v0.9.5.

**Pull request closed without merging**
